USE datphongkhachsan;
SET NAMES utf8mb4;
UPDATE hotels SET address = '453 Trường Sa, Hội An', description = 'Resort sinh thái nghỉ dưỡng bao quanh bởi thiên nhiên xanh mát, thích hợp cho các gia đình và cặp đôi tìm kiếm sự yên bình.' WHERE id = 3;
UPDATE hotels SET address = '402 Trần Phú, Phú Quốc', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 4;
UPDATE hotels SET address = '857 Lê Duẩn, Hà Nội', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 5;
UPDATE hotels SET address = '634 Trường Sa, Huế', description = 'Nổi bật với thiết kế thân thiện môi trường, sử dụng năng lượng mặt trời và cung cấp thực đơn ăn chay hữu cơ.' WHERE id = 6;
UPDATE hotels SET address = '237 Trần Phú, Đồng Hới', description = 'Điểm đến hoàn hảo cho kỳ nghỉ trăng mật, không gian lãng mạn, yên tĩnh, phục vụ bữa tối dưới ánh nến tại bãi biển.' WHERE id = 7;
UPDATE hotels SET address = '838 Lê Duẩn, Phú Quốc', description = 'Kiến trúc cổ điển kết hợp phong cách hoàng gia, cung cấp dịch vụ spa và hồ bơi vô cực độc quyền.' WHERE id = 8;
UPDATE hotels SET address = '959 Hai Bà Trưng, Phan Thiết', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 9;
UPDATE hotels SET address = '666 Lê Duẩn, Đồng Hới', description = 'Khách sạn lý tưởng cho những chuyến công tác với phòng hội nghị lớn, internet tốc độ cao và nhà hàng phục vụ 24/7.' WHERE id = 10;
UPDATE hotels SET address = '458 Điện Biên Phủ, Phú Quốc', description = 'Nổi bật với thiết kế thân thiện môi trường, sử dụng năng lượng mặt trời và cung cấp thực đơn ăn chay hữu cơ.' WHERE id = 11;
UPDATE hotels SET address = '891 Trường Sa, Vũng Tàu', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 12;
UPDATE hotels SET address = '154 Nguyễn Trãi, Phú Quốc', description = 'Trải nghiệm không gian sống thượng lưu với các phòng suite rộng rãi, ban công riêng và dịch vụ quản gia cá nhân.' WHERE id = 13;
UPDATE hotels SET address = '876 Tôn Đức Thắng, Hà Nội', description = 'Kiến trúc cổ điển kết hợp phong cách hoàng gia, cung cấp dịch vụ spa và hồ bơi vô cực độc quyền.' WHERE id = 14;
UPDATE hotels SET address = '750 Hai Bà Trưng, Hà Nội', description = 'Điểm đến hoàn hảo cho kỳ nghỉ trăng mật, không gian lãng mạn, yên tĩnh, phục vụ bữa tối dưới ánh nến tại bãi biển.' WHERE id = 15;
UPDATE hotels SET address = '52 Lý Thường Kiệt, Huế', description = 'Nổi bật với thiết kế thân thiện môi trường, sử dụng năng lượng mặt trời và cung cấp thực đơn ăn chay hữu cơ.' WHERE id = 16;
UPDATE hotels SET address = '530 Hai Bà Trưng, Nha Trang', description = 'Resort sinh thái nghỉ dưỡng bao quanh bởi thiên nhiên xanh mát, thích hợp cho các gia đình và cặp đôi tìm kiếm sự yên bình.' WHERE id = 17;
UPDATE hotels SET address = '18 Hai Bà Trưng, Hạ Long', description = 'Resort sinh thái nghỉ dưỡng bao quanh bởi thiên nhiên xanh mát, thích hợp cho các gia đình và cặp đôi tìm kiếm sự yên bình.' WHERE id = 18;
UPDATE hotels SET address = '727 Lý Thường Kiệt, Hạ Long', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 19;
UPDATE hotels SET address = '637 Điện Biên Phủ, Huế', description = 'Điểm đến hoàn hảo cho kỳ nghỉ trăng mật, không gian lãng mạn, yên tĩnh, phục vụ bữa tối dưới ánh nến tại bãi biển.' WHERE id = 20;
UPDATE hotels SET address = '379 Hoàng Sa, Đà Nẵng', description = 'Khách sạn tiêu chuẩn 5 sao với tầm nhìn hướng biển tuyệt đẹp, mang đến trải nghiệm nghỉ dưỡng đẳng cấp và sang trọng bậc nhất.' WHERE id = 21;
UPDATE hotels SET address = '151 Điện Biên Phủ, TP. Hồ Chí Minh', description = 'Khách sạn tiêu chuẩn 5 sao với tầm nhìn hướng biển tuyệt đẹp, mang đến trải nghiệm nghỉ dưỡng đẳng cấp và sang trọng bậc nhất.' WHERE id = 22;
UPDATE hotels SET address = '954 Tôn Đức Thắng, Sapa', description = 'Điểm đến hoàn hảo cho kỳ nghỉ trăng mật, không gian lãng mạn, yên tĩnh, phục vụ bữa tối dưới ánh nến tại bãi biển.' WHERE id = 23;
UPDATE hotels SET address = '474 Lê Lợi, Phan Thiết', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 24;
UPDATE hotels SET address = '484 Trường Sa, Hạ Long', description = 'Khách sạn lý tưởng cho những chuyến công tác với phòng hội nghị lớn, internet tốc độ cao và nhà hàng phục vụ 24/7.' WHERE id = 25;
UPDATE hotels SET address = '325 Võ Nguyên Giáp, Sapa', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 26;
UPDATE hotels SET address = '513 Lê Lợi, Cần Thơ', description = 'Điểm đến hoàn hảo cho kỳ nghỉ trăng mật, không gian lãng mạn, yên tĩnh, phục vụ bữa tối dưới ánh nến tại bãi biển.' WHERE id = 27;
UPDATE hotels SET address = '225 Tôn Đức Thắng, Đà Nẵng', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 28;
UPDATE hotels SET address = '210 Hai Bà Trưng, Hà Nội', description = 'Nổi bật với thiết kế thân thiện môi trường, sử dụng năng lượng mặt trời và cung cấp thực đơn ăn chay hữu cơ.' WHERE id = 29;
UPDATE hotels SET address = '116 Trường Sa, Phan Thiết', description = 'Nằm ngay trung tâm thành phố, tiện lợi cho việc di chuyển. Không gian thiết kế hiện đại, ấm cúng và đầy đủ tiện nghi.' WHERE id = 30;
UPDATE hotels SET address = '681 Phạm Văn Đồng, Nha Trang', description = 'Kiến trúc cổ điển kết hợp phong cách hoàng gia, cung cấp dịch vụ spa và hồ bơi vô cực độc quyền.' WHERE id = 31;
UPDATE hotels SET address = '15 Tôn Đức Thắng, Hà Nội', description = 'Nổi bật với thiết kế thân thiện môi trường, sử dụng năng lượng mặt trời và cung cấp thực đơn ăn chay hữu cơ.' WHERE id = 32;
UPDATE hotels SET address = '25 Điện Biên Phủ, Vũng Tàu', description = 'Điểm đến hoàn hảo cho kỳ nghỉ trăng mật, không gian lãng mạn, yên tĩnh, phục vụ bữa tối dưới ánh nến tại bãi biển.' WHERE id = 33;
UPDATE hotels SET address = '607 Lê Lợi, Hạ Long', description = 'Resort sinh thái nghỉ dưỡng bao quanh bởi thiên nhiên xanh mát, thích hợp cho các gia đình và cặp đôi tìm kiếm sự yên bình.' WHERE id = 34;
UPDATE hotels SET address = '570 Nguyễn Đình Chiểu, TP. Hồ Chí Minh', description = 'Khách sạn lý tưởng cho những chuyến công tác với phòng hội nghị lớn, internet tốc độ cao và nhà hàng phục vụ 24/7.' WHERE id = 35;
UPDATE hotels SET address = '368 Lê Duẩn, Hạ Long', description = 'Trải nghiệm không gian sống thượng lưu với các phòng suite rộng rãi, ban công riêng và dịch vụ quản gia cá nhân.' WHERE id = 36;
UPDATE hotels SET address = '488 Nguyễn Trãi, Phú Quốc', description = 'Resort sinh thái nghỉ dưỡng bao quanh bởi thiên nhiên xanh mát, thích hợp cho các gia đình và cặp đôi tìm kiếm sự yên bình.' WHERE id = 37;
UPDATE hotels SET address = '545 Điện Biên Phủ, TP. Hồ Chí Minh', description = 'Điểm đến hoàn hảo cho kỳ nghỉ trăng mật, không gian lãng mạn, yên tĩnh, phục vụ bữa tối dưới ánh nến tại bãi biển.' WHERE id = 38;
UPDATE hotels SET address = '552 Hai Bà Trưng, Phan Thiết', description = 'Khách sạn lý tưởng cho những chuyến công tác với phòng hội nghị lớn, internet tốc độ cao và nhà hàng phục vụ 24/7.' WHERE id = 39;
UPDATE hotels SET address = '784 Nguyễn Đình Chiểu, Hạ Long', description = 'Resort sinh thái nghỉ dưỡng bao quanh bởi thiên nhiên xanh mát, thích hợp cho các gia đình và cặp đôi tìm kiếm sự yên bình.' WHERE id = 40;
UPDATE hotels SET address = '360 Trần Phú, Quy Nhơn', description = 'Nổi bật với thiết kế thân thiện môi trường, sử dụng năng lượng mặt trời và cung cấp thực đơn ăn chay hữu cơ.' WHERE id = 41;
UPDATE hotels SET address = '674 Nguyễn Đình Chiểu, Cần Thơ', description = 'Trải nghiệm không gian sống thượng lưu với các phòng suite rộng rãi, ban công riêng và dịch vụ quản gia cá nhân.' WHERE id = 42;
DELETE FROM tour_activities;
INSERT INTO tour_activities (title, description, image_url) VALUES ('Tour Đảo Vip', 'Trải nghiệm tuyệt vời với Tour Đảo Vip. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/02561997-fc74-4f8d-9536-cdc6d42bb8dd.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Lặn Ngắm San Hô', 'Trải nghiệm tuyệt vời với Lặn Ngắm San Hô. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/050381c6-4336-4b27-bb8e-c690c1b5a22a.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Trải Nghiệm Dù Lượn', 'Trải nghiệm tuyệt vời với Trải Nghiệm Dù Lượn. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/0af5907b-8e4d-4da6-b148-bf1bb666fc8d.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Vé Công Viên Nước', 'Trải nghiệm tuyệt vời với Vé Công Viên Nước. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/34f427d0-28f6-4778-9533-cbb224eddbe4.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Khám Phá Hang Động', 'Trải nghiệm tuyệt vời với Khám Phá Hang Động. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/54c7683c-aa7f-42d8-96ee-9ad7eb2234fa.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Tour Thành Phố', 'Trải nghiệm tuyệt vời với Tour Thành Phố. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/6fae66c6-2ab0-47b1-95fa-475cc3084a59.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Vé Tắm Bùn Khoáng', 'Trải nghiệm tuyệt vời với Vé Tắm Bùn Khoáng. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/93f00e04-3f80-4f61-bdd0-04620ab2605f.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Cắm Trại Rừng Thông', 'Trải nghiệm tuyệt vời với Cắm Trại Rừng Thông. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/a47f0065-fe22-4f91-ba67-8073900ce0ed.webp');
INSERT INTO tour_activities (title, description, image_url) VALUES ('Du Thuyền Ngắm Hoàng Hôn', 'Trải nghiệm tuyệt vời với Du Thuyền Ngắm Hoàng Hôn. Dịch vụ trọn gói chất lượng cao.', '/uploads/activities/fee56bb6-e618-4500-b440-e51ec0f0843b.jpg');
