USE datphongkhachsan;
UPDATE hotels SET address = '569 Võ Nguyên Giáp, Đà Nẵng' WHERE id = 3;
UPDATE hotels SET address = '631 Nguyễn Trãi, Đà Lạt' WHERE id = 4;
UPDATE hotels SET address = '383 Nguyễn Trãi, Phú Quốc' WHERE id = 5;
UPDATE hotels SET address = '475 Lý Thường Kiệt, Hội An' WHERE id = 6;
UPDATE hotels SET address = '59 Lê Duẩn, Sapa' WHERE id = 7;
UPDATE hotels SET address = '363 Lý Thường Kiệt, Phú Quốc' WHERE id = 8;
UPDATE hotels SET address = '885 Nguyễn Huệ, Đà Lạt' WHERE id = 9;
UPDATE hotels SET address = '332 Hai Bà Trưng, Hội An' WHERE id = 10;
UPDATE hotels SET address = '778 Nguyễn Trãi, TP. Hồ Chí Minh' WHERE id = 11;
UPDATE hotels SET address = '463 Lê Lợi, Phú Quốc' WHERE id = 12;
UPDATE hotels SET address = '186 Hai Bà Trưng, Đà Lạt' WHERE id = 13;
UPDATE hotels SET address = '81 Võ Nguyên Giáp, Đà Lạt' WHERE id = 14;
UPDATE hotels SET address = '807 Lý Thường Kiệt, Quy Nhơn' WHERE id = 15;
UPDATE hotels SET address = '525 Lý Thường Kiệt, Đà Nẵng' WHERE id = 16;
UPDATE hotels SET address = '355 Phạm Văn Đồng, Hà Nội' WHERE id = 17;
UPDATE hotels SET address = '271 Võ Nguyên Giáp, TP. Hồ Chí Minh' WHERE id = 18;
UPDATE hotels SET address = '104 Hai Bà Trưng, Phú Quốc' WHERE id = 19;
UPDATE hotels SET address = '885 Điện Biên Phủ, Đà Lạt' WHERE id = 20;
UPDATE hotels SET address = '645 Lê Duẩn, Đà Lạt' WHERE id = 21;
UPDATE hotels SET address = '937 Nguyễn Trãi, Phú Quốc' WHERE id = 22;
UPDATE hotels SET address = '741 Nguyễn Huệ, TP. Hồ Chí Minh' WHERE id = 23;
UPDATE hotels SET address = '360 Nguyễn Huệ, TP. Hồ Chí Minh' WHERE id = 24;
UPDATE hotels SET address = '750 Trần Phú, Đà Lạt' WHERE id = 25;
UPDATE hotels SET address = '630 Hai Bà Trưng, Sapa' WHERE id = 26;
UPDATE hotels SET address = '673 Hai Bà Trưng, TP. Hồ Chí Minh' WHERE id = 27;
UPDATE hotels SET address = '708 Điện Biên Phủ, Hà Nội' WHERE id = 28;
UPDATE hotels SET address = '65 Nguyễn Trãi, Đà Nẵng' WHERE id = 29;
UPDATE hotels SET address = '113 Điện Biên Phủ, Đà Nẵng' WHERE id = 30;
UPDATE hotels SET address = '611 Lê Duẩn, TP. Hồ Chí Minh' WHERE id = 31;
UPDATE hotels SET address = '99 Lê Lợi, Sapa' WHERE id = 32;
UPDATE hotels SET address = '798 Hai Bà Trưng, Sapa' WHERE id = 33;
UPDATE hotels SET address = '871 Lý Thường Kiệt, Phú Quốc' WHERE id = 34;
UPDATE hotels SET address = '972 Nguyễn Trãi, Hà Nội' WHERE id = 35;
UPDATE hotels SET address = '228 Điện Biên Phủ, Nha Trang' WHERE id = 36;
UPDATE hotels SET address = '849 Nguyễn Trãi, Nha Trang' WHERE id = 37;
UPDATE hotels SET address = '744 Lê Duẩn, Hà Nội' WHERE id = 38;
UPDATE hotels SET address = '18 Phạm Văn Đồng, Quy Nhơn' WHERE id = 39;
UPDATE hotels SET address = '117 Lê Duẩn, Hà Nội' WHERE id = 40;
UPDATE hotels SET address = '912 Hai Bà Trưng, Đà Nẵng' WHERE id = 41;
UPDATE hotels SET address = '98 Võ Nguyên Giáp, Hội An' WHERE id = 42;

